---
hosts: all
become: yes
tasks:
  - name: install apache2
    ansible.builtin.apt:
      name: apache2
      update_cache: yes
      state: present
  - name: copy file with owner and permissions
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html
      owner: root
      group: root
      mode: '0664'
